CREATE TABLE products (
  product_id INT PRIMARY KEY,
  sku VARCHAR(50) UNIQUE,
  name VARCHAR(255),
  brand VARCHAR(100),
  category VARCHAR(100),          -- e.g., “Skincare”, “Makeup”
  sub_category VARCHAR(100),      -- e.g., “Cleanser”, “Serum”, “Foundation”
  skin_type VARCHAR(100),         -- comma-separated: “oily,dry,normal,sensitive”
  concern VARCHAR(255),           -- e.g., “acne,aging,hyperpigmentation”
  ingredients TEXT,                -- string list of ingredients
  price DECIMAL(10,2),             -- in your currency
  currency VARCHAR(10),
  size_ml DECIMAL(10,2),            -- product volume / size in ml
  rating_avg DECIMAL(3,2),        -- average rating, e.g. 4.50
  rating_count INT,
  description TEXT,
  image_url VARCHAR(500)
);
INSERT INTO products (product_id, sku, name, brand, category, sub_category, skin_type, concern,
                      ingredients, price, currency, size_ml, rating_avg, rating_count, description, image_url)
VALUES
(1, 'SKN001', 'Hydrating Facial Cleanser', 'GlowSkin', 'Skincare', 'Cleanser',
 'dry,normal', 'dehydration', 'Water, Glycerin, Ceramide, Hyaluronic Acid', 12.99, 'USD', 200, 4.5, 120,
 'A gentle hydrating cleanser for daily use.', 'https://example.com/image1.jpg'),
(2, 'SKN002', 'Mattifying Gel Cleanser', 'PureFace', 'Skincare', 'Cleanser',
 'oily,combination', 'oiliness,acne', 'Water, Salicylic Acid, Aloe Vera, Niacinamide', 14.50, 'USD', 180, 4.2, 98,
 'Oil control gel cleanser to unclog pores.', 'https://example.com/image2.jpg'),
(3, 'SKN003', 'AHA Exfoliating Toner', 'SmoothDerm', 'Skincare', 'Toner',
 'normal,oily,combination', 'texture,brightening', 'Glycolic Acid, Water, Witch Hazel, Lactic Acid', 18.00, 'USD', 150, 4.7, 210,
 'Exfoliating toner to reveal smooth skin.', 'https://example.com/image3.jpg'),
(4, 'SKN004', 'Vitamin C Brightening Serum', 'RadiantYou', 'Skincare', 'Serum',
 'dull,aging,normal', 'dark spots,brightness', 'Ascorbic Acid, Ferulic Acid, Vitamin E, Water', 25.75, 'USD', 30, 4.8, 340,
 'Powerful vitamin C serum for glowing skin.', 'https://example.com/image4.jpg'),
(5, 'SKN005', 'Retinol Night Serum', 'YouthRevive', 'Skincare', 'Serum',
 'aging,normal,dry', 'wrinkles,firmness', 'Retinol, Peptides, Squalane, Glycerin', 30.00, 'USD', 30, 4.4, 150,
 'Retinol serum to reduce fine lines over time.', 'https://example.com/image5.jpg'),
(6, 'SKN006', 'Hyaluronic Hydration Booster', 'AquaPlenish', 'Skincare', 'Serum',
 'dry,normal', 'dehydration', 'Water, Hyaluronic Acid, Panthenol, Sodium PCA', 20.50, 'USD', 50, 4.6, 200,
 'Boosts skin hydration instantly.', 'https://example.com/image6.jpg'),
(7, 'SKN007', 'Niacinamide 10% + Zinc Serum', 'ClearSkin Lab', 'Skincare', 'Serum',
 'oily,combination,acne-prone', 'acne,pores', 'Niacinamide, Zinc PCA, Glycerin, Water', 22.00, 'USD', 30, 4.3, 180,
 'Reduces blemishes and refines pores.', 'https://example.com/image7.jpg'),
(8, 'SKN008', 'SPF Moisturizer Broad Spectrum 50', 'SunShield', 'Skincare', 'Moisturizer',
 'all,normal,dry', 'sun protection', 'Zinc Oxide, Water, Glycerin, Vitamin E', 28.00, 'USD', 50, 4.9, 420,
 'Daily moisturizer with high SPF.', 'https://example.com/image8.jpg'),
(9, 'SKN009', 'Oil-Free Moisturizer', 'FreshFeel', 'Skincare', 'Moisturizer',
 'oily,combination', 'shine,hydration', 'Water, Dimethicone, Glycerin, Green Tea Extract', 15.99, 'USD', 60, 4.1, 95,
 'Lightweight moisturizer that won’t clog pores.', 'https://example.com/image9.jpg'),
(10, 'SKN010', 'Barrier Repair Cream', 'DermGuard', 'Skincare', 'Moisturizer',
 'dry,sensitive', 'barrier,redness', 'Ceramide, Cholesterol, Fatty Acids, Water', 32.00, 'USD', 50, 4.8, 220,
 'Strengthens skin barrier and soothes.', 'https://example.com/image10.jpg'),
(11, 'SKN011', 'Overnight Repair Mask', 'SleepSkin', 'Skincare', 'Mask',
 'dry,aging', 'repair,firmness', 'Shea Butter, Peptides, Squalane, Hyaluronic Acid', 29.99, 'USD', 75, 4.5, 160,
 'Rich overnight mask to restore skin while you sleep.', 'https://example.com/image11.jpg'),
(12, 'SKN012', 'Clay Purifying Mask', 'PureFace', 'Skincare', 'Mask',
 'oily,acne-prone', 'impurities,excess oil', 'Kaolin Clay, Bentonite, Charcoal, Aloe Vera', 19.50, 'USD', 100, 4.2, 130,
 'Detoxifying clay mask for deep cleansing.', 'https://example.com/image12.jpg'),
(13, 'SKN013', 'Eye Cream with Caffeine', 'BrightEyes', 'Skincare', 'Eye Treatment',
 'all', 'dark circles,puffiness', 'Caffeine, Peptides, Hyaluronic Acid, Water', 24.00, 'USD', 15, 4.3, 110,
 'Revitalizing eye cream to reduce puffiness.', 'https://example.com/image13.jpg'),
(14, 'SKN014', 'SPF 30 Tinted Sunscreen', 'GlowTone', 'Makeup', 'Sunscreen/Foundation',
 'all', 'sun protection,even tone', 'Zinc Oxide, Titanium Dioxide, Iron Oxides, Water', 33.00, 'USD', 45, 4.6, 250,
 'Tinted sunscreen for daily wear and coverage.', 'https://example.com/image14.jpg'),
(15, 'SKN015', 'Matte Liquid Foundation', 'CoverArt', 'Makeup', 'Foundation',
 'oily,combination', 'shine control', 'Water, Dimethicone, Silica, Iron Oxides', 28.75, 'USD', 30, 4.2, 140,
 'Long-wear foundation with a matte finish.', 'https://example.com/image15.jpg'),
(16, 'SKN016', 'Hydrating Cushion Foundation', 'CushionLux', 'Makeup', 'Foundation',
 'dry,normal', 'hydration,coverage', 'Water, Glycerin, Hyaluronic Acid, Iron Oxides', 35.00, 'USD', 50, 4.7, 180,
 'Cushion foundation for dewy, natural skin.', 'https://example.com/image16.jpg'),
(17, 'SKN017', 'Liquid Blush', 'SoftCheek', 'Makeup', 'Blush',
 'all', 'color', 'Water, Talc, Iron Oxides, Glycerin', 18.00, 'USD', 15, 4.1, 75,
 'Creamy liquid blush for a natural flush.', 'https://example.com/image17.jpg'),
(18, 'SKN018', 'Baked Highlighter', 'GlowBeam', 'Makeup', 'Highlighter',
 'all', 'radiance', 'Mica, Silica, Talc, Dimethicone', 22.00, 'USD', 10, 4.5, 100,
 'Shimmery highlighter for glowing skin.', 'https://example.com/image18.jpg'),
(19, 'SKN019', 'Waterproof Mascara', 'LashLift', 'Makeup', 'Mascara',
 'all', 'volume,length', 'Aqua, Beeswax, Carbon Black, Glycerin', 17.50, 'USD', 12, 4.0, 150,
 'Volumizing waterproof mascara.', 'https://example.com/image19.jpg'),
(20, 'SKN020', 'Liquid Eyeliner', 'LinePro', 'Makeup', 'Eyeliner',
 'all', 'definition', 'Water, Styrene/Acrylates, Pigments, Aminomethyl Propanol', 16.00, 'USD', 3, 4.2, 90,
 'Smooth glide liquid eyeliner.', 'https://example.com/image20.jpg'),
(21, 'SKN021', 'Volumizing Shampoo', 'HairGlow', 'Haircare', 'Shampoo',
 'all', 'volume,thickness', 'Water, SLS, Panthenol, Hydrolyzed Keratin', 12.00, 'USD', 250, 4.3, 200,
 'Gentle shampoo for fuller hair.', 'https://example.com/image21.jpg'),
(22, 'SKN022', 'Repairing Hair Conditioner', 'HairGlow', 'Haircare', 'Conditioner',
 'all', 'damage,split ends', 'Water, Shea Butter, Keratin, Argan Oil', 14.50, 'USD', 200, 4.4, 180,
 'Deep conditioner for repairing hair damage.', 'https://example.com/image22.jpg'),
(23, 'SKN023', 'Argan Oil Hair Serum', 'SilkStrand', 'Haircare', 'Hair Serum',
 'dry,all', 'frizz,shine', 'Argan Oil, Vitamin E, Cyclomethicone', 19.00, 'USD', 50, 4.6, 150,
 'Lightweight serum for smooth frizz-free hair.', 'https://example.com/image23.jpg'),
(24, 'SKN024', 'Dry Scalp Treatment', 'ScalpRelief', 'Haircare', 'Treatment',
 'dry', 'flakiness,itchy scalp', 'Salicylic Acid, Tea Tree Oil, Water, Glycerin', 18.75, 'USD', 100, 4.2, 110,
 'Scalp treatment to soothe dryness.', 'https://example.com/image24.jpg'),
(25, 'SKN025', 'Volumizing Dry Shampoo', 'FreshSpray', 'Haircare', 'Dry Shampoo',
 'oily,all', 'oiliness,refresh', 'Starch, Alcohol Denat, Fragrance', 13.00, 'USD', 150, 4.1, 140,
 'Refresh hair without water.', 'https://example.com/image25.jpg'),
(26, 'SKN026', 'Lip Balm SPF 15', 'LipGuard', 'Makeup', 'Lip Care',
 'all', 'sun protection,dry lips', 'Beeswax, Shea Butter, Titanium Dioxide, Vitamin E', 8.50, 'USD', 10, 4.5, 200,
 'Nourishing lip balm with light SPF.', 'https://example.com/image26.jpg'),
(27, 'SKN027', 'Matte Lipstick', 'ColorPop', 'Makeup', 'Lipstick',
 'all', 'color,long wear', 'Caster Oil, Silica, Iron Oxides, Dimethicone', 12.00, 'USD', 4, 4.3, 180,
 'Long-lasting matte lipstick.', 'https://example.com/image27.jpg'),
(28, 'SKN028', 'Hydrating Lip Gloss', 'GlossyKiss', 'Makeup', 'Lip Gloss',
 'dry,normal', 'shine,moisture', 'Polybutene, Glycerin, Vitamin E, Water', 10.00, 'USD', 6, 4.2, 120,
 'Moisturizing high-shine lip gloss.', 'https://example.com/image28.jpg'),
(29, 'SKN029', 'Makeup Setting Spray', 'FixMist', 'Makeup', 'Setting Spray',
 'all', 'longevity', 'Water, Alcohol Denat., Glycerin, Fragrance', 14.00, 'USD', 100, 4.0, 95,
 'Keeps makeup locked in all day.', 'https://example.com/image29.jpg'),
(30, 'SKN030', 'Vitamin E Night Cream', 'NutriSkin', 'Skincare', 'Moisturizer',
 'normal,dry', 'repair,antioxidant', 'Water, Tocopherol, Shea Butter, Ceramide', 24.50, 'USD', 50, 4.6, 170,
 'Rich night cream full of antioxidants.', 'https://example.com/image30.jpg'),
(31, 'SKN031', 'Peptide Firming Serum', 'FirmUp', 'Skincare', 'Serum',
 'aging,normal', 'firmness,wrinkles', 'Peptides, Water, Glycerin, Dimethicone', 27.00, 'USD', 30, 4.3, 140,
 'Boosts skin elasticity with peptides.', 'https://example.com/image31.jpg'),
(32, 'SKN032', 'Charcoal Pore Cleanser', 'DeepClean', 'Skincare', 'Cleanser',
 'oily,acne-prone', 'clogged pores', 'Charcoal, Clay, Water, Glycerin', 16.00, 'USD', 180, 4.1, 100,
 'Deep cleansing charcoal cleanser.', 'https://example.com/image32.jpg'),
(33, 'SKN033', 'Brightening Sheet Mask', 'GlowMask', 'Skincare', 'Mask',
 'dull,normal', 'radiance', 'Water, Niacinamide, Aloe Vera, Glycerin', 5.75, 'USD', 25, 4.7, 90,
 'Single-use sheet mask for luminous skin.', 'https://example.com/image33.jpg'),
(34, 'SKN034', 'Sensitive Skin Soothing Mist', 'CalmAura', 'Skincare', 'Toner',
 'sensitive,dry', 'redness,irritation', 'Chamomile, Glycerin, Water, Panthenol', 13.00, 'USD', 120, 4.5, 110,
 'Cooling mist to calm irritated skin.', 'https://example.com/image34.jpg'),
(35, 'SKN035', 'Mineral Sunscreen SPF 50', 'PureShield', 'Skincare', 'Sunscreen',
 'all', 'sun protection', 'Zinc Oxide, Titanium Dioxide, Water, Glycerin', 34.00, 'USD', 60, 4.8, 310,
 'Physical sunscreen for sensitive skin.', 'https://example.com/image35.jpg'),
(36, 'SKN036', 'Oil-Control Primer', 'SmoothBase', 'Makeup', 'Primer',
 'oily,combination', 'shine control', 'Silica, Water, Dimethicone, Glycerin', 19.00, 'USD', 30, 4.2, 130,
 'Mattifying primer to reduce shine.', 'https://example.com/image36.jpg'),
(37, 'SKN037', 'Illuminating Primer', 'GlowBase', 'Makeup', 'Primer',
 'dry,normal', 'radiance', 'Glycerin, Mica, Water, Dimethicone', 21.00, 'USD', 30, 4.4, 120,
 'Primer that gives subtle glow.', 'https://example.com/image37.jpg'),
(38, 'SKN038', 'Water-Based BB Cream', 'BBPerfect', 'Makeup', 'BB Cream',
 'normal,combination', 'light coverage,even tone', 'Water, Dimethicone, Iron Oxides, Glycerin', 26.00, 'USD', 40, 4.3, 140,
 'BB cream for natural everyday look.', 'https://example.com/image38.jpg'),
(39, 'SKN039', 'Contour Stick', 'SculptPro', 'Makeup', 'Contour',
 'all', 'definition', 'Hydrogenated Vegetable Oil, Talc, Iron Oxides, Dimethicone', 23.00, 'USD', 15, 4.1, 100,
 'Cream stick for sculpting your features.', 'https://example.com/image39.jpg'),
(40, 'SKN040', 'Brow Gel Clear', 'BrowDefine', 'Makeup', 'Brow',
 'all', 'hold,shape', 'Water, Glycerin, Acrylates, Polymers', 15.00, 'USD', 10, 4.2, 90,
 'Clear gel to shape and set eyebrows.', 'https://example.com/image40.jpg'),
(41, 'SKN041', 'Waterproof Brow Pencil', 'BrowSharp', 'Makeup', 'Brow',
 'all', 'definition', 'Wax, Iron Oxides, Talc, Dimethicone', 17.00, 'USD', 2, 4.0, 110,
 'Long-lasting waterproof brow pencil.', 'https://example.com/image41.jpg'),
(42, 'SKN042', 'Makeup Remover Balm', 'DissolveIt', 'Skincare', 'Cleanser',
 'all', 'makeup removal', 'Coconut Oil, Shea Butter, Glycerin, Water', 22.00, 'USD', 120, 4.6, 200,
 'Balmy cleanser to remove stubborn makeup.', 'https://example.com/image42.jpg'),
(43, 'SKN043', 'Peel-Off Mask', 'GlowPeel', 'Skincare', 'Mask',
 'normal,oily', 'dead skin,texture', 'Polyvinyl Alcohol, Charcoal, Aloe Vera, Water', 12.00, 'USD', 50, 4.2, 100,
 'Peel-off mask that detoxifies and smooths skin.', 'https://example.com/image43.jpg'),
(44, 'SKN044', 'Superfood Face Oil', 'PlantEssence', 'Skincare', 'Oil',
 'dry,normal', 'nutrition,glow', 'Jojoba Oil, Rosehip Oil, Squalane, Vitamin E', 27.00, 'USD', 30, 4.7, 150,
 'Natural face oil packed with essential nutrients.', 'https://example.com/image44.jpg'),
(45, 'SKN045', 'Mattifying Face Mist', 'FreshMatte', 'Skincare', 'Toner',
 'oily,combination', 'oil control,refresh', 'Water, Witch Hazel, Salicylic Acid, Glycerin', 15.00, 'USD', 100, 4.1, 90,
 'Mist to refresh skin and control shine.', 'https://example.com/image45.jpg'),
(46, 'SKN046', 'Lip Care Overnight Mask', 'SleepLips', 'Makeup', 'Lip Care',
 'dry,all', 'repair,moisture', 'Shea Butter, Peptides, Glycerin, Water', 14.00, 'USD', 20, 4.5, 120,
 'Hydrating overnight lip mask.', 'https://example.com/image46.jpg'),
(47, 'SKN047', 'Cleansing Oil', 'SilkyClean', 'Skincare', 'Cleanser',
 'dry,normal', 'makeup removal,hydration', 'Sunflower Oil, Glycerin, Water, Vitamin E', 18.50, 'USD', 150, 4.4, 160,
 'Gentle oil cleanser that melts makeup.', 'https://example.com/image47.jpg'),
(48, 'SKN048', 'Rose Water Toner', 'BloomTonic', 'Skincare', 'Toner',
 'sensitive,normal', 'soothing,hydration', 'Rose Water, Glycerin, Water, Aloe Vera', 13.50, 'USD', 200, 4.6, 140,
 'Refreshing rose water toner for sensitive skin.', 'https://example.com/image48.jpg'),
(49, 'SKN049', 'Overnight Retinoid Cream', 'RetinoRevive', 'Skincare', 'Moisturizer',
 'aging,normal', 'wrinkles,firmness', 'Retinoid, Peptides, Squalane, Ceramide', 35.00, 'USD', 45, 4.5, 130,
 'Overnight retinoid-based cream for anti-aging.', 'https://example.com/image49.jpg'),
(50, 'SKN050', 'Brightening Essence', 'GlowEssence', 'Skincare', 'Essence',
 'dull,aging', 'radiance,texture', 'Niacinamide, Glycerin, Water, Panthenol', 23.00, 'USD', 75, 4.4, 150,
 'Light essence to brighten and hydrate.', 'https://example.com/image50.jpg'),
(51, 'SKN051', 'Clarifying BHA Lotion', 'ClearSkin Lab', 'Skincare', 'Serum',
 'oily,acne-prone', 'blackheads,pores', 'Salicylic Acid, Water, Glycerin, Aloe', 24.00, 'USD', 60, 4.3, 120,
 'Gentle BHA lotion for exfoliation.', 'https://example.com/image51.jpg'),
(52, 'SKN052', 'Sleeping Water Gel', 'AquaDream', 'Skincare', 'Moisturizer',
 'normal,oily', 'hydration,lightweight', 'Water, Glycerin, Sodium Hyaluronate, Niacinamide', 26.00, 'USD', 50, 4.6, 200,
 'Light gel that hydrates overnight.', 'https://example.com/image52.jpg'),
(53, 'SKN053', 'Firming Eye Serum', 'LiftEyes', 'Skincare', 'Eye Treatment',
 'aging,normal', 'wrinkles,firmness', 'Peptides, Caffeine, Water, Glycerin', 28.00, 'USD', 20, 4.3, 140,
 'Firming eye serum to reduce fine lines.', 'https://example.com/image53.jpg'),
(54, 'SKN054', 'Brightening Peel Pads', 'GlowPads', 'Skincare', 'Exfoliator',
 'dull,oily', 'texture,hyperpigmentation', 'Glycolic Acid, Lactic Acid, Water, Witch Hazel', 22.00, 'USD', 60, 4.4, 160,
 'Pre-soaked exfoliating pads for quick glow.', 'https://example.com/image54.jpg'),
(55, 'SKN055', 'Gentle Exfoliating Scrub', 'SmoothScrub', 'Skincare', 'Scrub',
 'normal,combination', 'texture,dead skin', 'Jojoba Beads, Glycerin, Water, Shea Butter', 17.00, 'USD', 100, 4.1, 110,
 'Physical scrub for gentle exfoliation.', 'https://example.com/image55.jpg'),
(56, 'SKN056', 'Blue Light Defense Serum', 'ScreenShield', 'Skincare', 'Serum',
 'all,normal', 'blue light,dullness', 'Niacinamide, Antioxidants, Glycerin, Water', 29.00, 'USD', 30, 4.2, 90,
 'Helps defend skin from digital screen damage.', 'https://example.com/image56.jpg'),
(57, 'SKN057', 'Firming Neck Cream', 'NeckLift', 'Skincare', 'Treatment',
 'aging,normal', 'sagging,firmness', 'Peptides, Hyaluronic Acid, Water, Shea Butter', 32.50, 'USD', 40, 4.3, 120,
 'Firming cream specifically for neck area.', 'https://example.com/image57.jpg'),
(58, 'SKN058', 'Sensitive Cleansing Foam', 'SoftCleanse', 'Skincare', 'Cleanser',
 'sensitive,normal', 'irritation,makeup removal', 'Water, Glycerin, Mild Surfactants, Aloe Vera', 16.50, 'USD', 200, 4.4, 130,
 'Gentle foam wash for sensitive skin.', 'https://example.com/image58.jpg'),
(59, 'SKN059', 'Balancing Face Oil', 'BalanceOil', 'Skincare', 'Oil',
 'combination,normal', 'balance,glow', 'Squalane, Jojoba Oil, Vitamin E, Rosehip Oil', 24.00, 'USD', 30, 4.5, 150,
 'Light facial oil that balances skin.', 'https://example.com/image59.jpg'),
(60, 'SKN060', 'Brightening Eye Cream', 'GlowEyes', 'Skincare', 'Eye Treatment',
 'dull,aging', 'dark circles,firmness', 'Vitamin C, Peptides, Water, Glycerin', 26.00, 'USD', 15, 4.4, 140,
 'Eye cream to brighten under-eyes.', 'https://example.com/image60.jpg'),
(61, 'SKN061', 'Tinted Lip Balm', 'SheerTint', 'Makeup', 'Lip Care',
 'all', 'color,moisture', 'Beeswax, Shea Butter, Iron Oxides, Vitamin E', 11.00, 'USD', 8, 4.3, 90,
 'Sheer lip balm with a hint of color.', 'https://example.com/image61.jpg'),
(62, 'SKN062', 'Concealer Stick', 'CoverStick', 'Makeup', 'Concealer',
 'all', 'coverage,blemishes', 'Dimethicone, Iron Oxides, Water, Glycerin', 20.00, 'USD', 10, 4.2, 120,
 'Creamy stick concealer for imperfection coverage.', 'https://example.com/image62.jpg'),
(63, 'SKN063', 'Liquid Highlighter', 'LumiDrop', 'Makeup', 'Highlighter',
 'all', 'radiance', 'Mica, Water, Glycerin, Dimethicone', 24.00, 'USD', 15, 4.4, 110,
 'Dewy liquid highlighter for luminous skin.', 'https://example.com/image63.jpg'),
(64, 'SKN064', 'Cream Blush Stick', 'CreamyCheek', 'Makeup', 'Blush',
 'all', 'soft color', 'Hydrogenated Vegetable Oil, Iron Oxides, Dimethicone, Talc', 19.00, 'USD', 12, 4.1, 95,
 'Soft cream blush for a natural flush.', 'https://example.com/image64.jpg'),
(65, 'SKN065', 'Setting Powder Translucent', 'PowderFine', 'Makeup', 'Powder',
 'oily,all', 'oil control,finish', 'Talc, Silica, Magnesium Stearate', 18.00, 'USD', 20, 4.0, 80,
 'Lightweight translucent powder for setting makeup.', 'https://example.com/image65.jpg'),
(66, 'SKN066', 'Tinted Moisturizer SPF 25', 'ToneMoist', 'Makeup', 'Moisturizer/Foundation',
 'normal,dry', 'hydration,coverage,spf', 'Water, Dimethicone, Iron Oxides, Glycerin', 29.00, 'USD', 45, 4.5, 170,
 'Tinted moisturizer with SPF for daily wear.', 'https://example.com/image66.jpg'),
(67, 'SKN067', 'Purifying Scalp Scrub', 'HeadClean', 'Haircare', 'Treatment',
 'oily', 'dandruff,cleansing', 'Sugar, Salicylic Acid, Water, Glycerin', 16.00, 'USD', 120, 4.3, 100,
 'Exfoliating scrub for oily, flaky scalp.', 'https://example.com/image67.jpg'),
(68, 'SKN068', 'Heat Protectant Spray', 'ThermalGuard', 'Haircare', 'Spray',
 'all', 'heat damage', 'Silicone, Water, Panthenol, Fragrance', 15.50, 'USD', 200, 4.2, 130,
 'Prevents hair damage from styling tools.', 'https://example.com/image68.jpg'),
(69, 'SKN069', 'Volumizing Mousse', 'LiftFoam', 'Haircare', 'Styling',
 'fine,flat', 'volume,hold', 'Water, Alcohol, Polymers, Fragrance', 14.00, 'USD', 150, 4.1, 110,
 'Lightweight mousse for big volume.', 'https://example.com/image69.jpg'),
(70, 'SKN070', 'Deep Conditioning Hair Mask', 'SilkMask', 'Haircare', 'Mask',
 'dry,damaged', 'repair,softness', 'Shea Butter, Keratin, Argan Oil, Water', 20.00, 'USD', 200, 4.6, 140,
 'Rich hair mask to restore softness.', 'https://example.com/image70.jpg'),
(71, 'SKN071', 'Brow and Lash Serum', 'GrowLash', 'Makeup', 'Treatment',
 'all', 'growth,strength', 'Peptides, Biotin, Water, Glycerin', 22.00, 'USD', 5, 4.4, 120,
 'Serum to support brow and lash growth.', 'https://example.com/image71.jpg'),
(72, 'SKN072', 'Brightening Face Wash', 'GlowWash', 'Skincare', 'Cleanser',
 'dull,normal', 'brightening', 'Vitamin C, Water, Glycerin, Aloe Vera', 15.00, 'USD', 180, 4.3, 130,
 'Gentle wash to brighten complexion.', 'https://example.com/image72.jpg'),
(73, 'SKN073', 'Smoothing Toner Pads', 'TonePads', 'Skincare', 'Toner',
 'rough,texture', 'exfoliation,refinement', 'Salicylic Acid, Lactic Acid, Water, Witch Hazel', 21.00, 'USD', 60, 4.4, 140,
 'Pre-soaked pads to smooth skin texture.', 'https://example.com/image73.jpg'),
(74, 'SKN074', 'Anti-Redness Cream', 'CalmSkin', 'Skincare', 'Moisturizer',
 'sensitive,rosacea', 'redness,irritation', 'Azelaic Acid, Niacinamide, Glycerin, Water', 25.00, 'USD', 50, 4.5, 130,
 'Cream to soothe redness and calm skin.', 'https://example.com/image74.jpg'),
(75, 'SKN075', 'Collagen Boost Cream', 'FirmSkin', 'Skincare', 'Moisturizer',
 'aging,normal', 'firmness,elasticity', 'Hydrolyzed Collagen, Peptides, Water, Glycerin', 28.00, 'USD', 50, 4.4, 150,
 'Boosts skin elasticity with collagen.', 'https://example.com/image75.jpg'),
(76, 'SKN076', 'Detoxifying Clay Cleanser', 'DetoxClean', 'Skincare', 'Cleanser',
 'oily,combination', 'impurities,oil', 'Kaolin, Bentonite, Water, Glycerin', 17.00, 'USD', 180, 4.2, 110,
 'Deep pore cleansing clay-based wash.', 'https://example.com/image76.jpg'),
(77, 'SKN077', 'Brightening Cica Balm', 'CicaCalm', 'Skincare', 'Treatment',
 'sensitive,normal', 'irritation,repair', 'Centella Asiatica, Glycerin, Squalane, Water', 23.00, 'USD', 40, 4.6, 140,
 'Soothing balm with centella for redness.', 'https://example.com/image77.jpg'),
(78, 'SKN078', 'Multi-Peptide Eye Cream', 'PeptiEyes', 'Skincare', 'Eye Treatment',
 'aging,normal', 'wrinkles,firmness', 'Peptides, Hyaluronic Acid, Water, Glycerin', 27.00, 'USD', 15, 4.5, 135,
 'Eye cream packed with peptides for anti-aging.', 'https://example.com/image78.jpg'),
(79, 'SKN079', 'Dark Spot Corrector', 'SpotClear', 'Skincare', 'Treatment',
 'hyperpigmentation,aging', 'dark spots', 'Niacinamide, Tranexamic Acid, Water, Glycerin', 30.00, 'USD', 30, 4.4, 120,
 'Serum to fade dark spots and even skin tone.', 'https://example.com/image79.jpg'),
(80, 'SKN080', 'Makeup Removing Micellar Water', 'PureMicel', 'Skincare', 'Cleanser',
 'all', 'makeup removal', 'Water, Glycerin, PEG-6 Caprylic/Capric Glycerides, Fragrance', 12.00, 'USD', 300, 4.5, 190,
 'Gentle micellar water for daily cleansing.', 'https://example.com/image80.jpg'),
(81, 'SKN081', 'Post-Workout Facial Mist', 'RefreshMist', 'Skincare', 'Toner',
 'all', 'freshen,hydrate', 'Water, Glycerin, Cucumber Extract, Aloe', 14.00, 'USD', 150, 4.3, 100,
 'Hydrating mist to refresh skin after exercise.', 'https://example.com/image81.jpg'),
(82, 'SKN082', 'Daily Vitamin Barrier Serum', 'BarrierBoost', 'Skincare', 'Serum',
 'all,normal', 'barrier,hydration', 'Ceramide, Niacinamide, Squalane, Water', 28.00, 'USD', 30, 4.6, 160,
 'Serum to strengthen skin barrier daily.', 'https://example.com/image82.jpg'),
(83, 'SKN083', 'Exfoliating Enzyme Mask', 'FruitPeel', 'Skincare', 'Mask',
 'dull,normal', 'texture,brightening', 'Pumpkin Enzymes, Papaya Enzymes, Water, Glycerin', 24.00, 'USD', 75, 4.4, 120,
 'Gentle enzyme mask for smooth, radiant skin.', 'https://example.com/image83.jpg'),
(84, 'SKN084', 'Brightening Sleeping Pack', 'GlowSleep', 'Skincare', 'Mask',
 'dull,aging', 'brightening,repair', 'Niacinamide, Ceramide, Squalane, Water', 26.00, 'USD', 80, 4.5, 140,
 'Hydrating overnight pack for glowing skin.', 'https://example.com/image84.jpg'),
(85, 'SKN085', 'Oil-Balancing Serum', 'BalanceIt', 'Skincare', 'Serum',
 'oily,combination', 'shine,pores', 'Niacinamide, Zinc PCA, Water, Glycerin', 23.00, 'USD', 30, 4.3, 150,
 'Serum to regulate oil production and minimize pores.', 'https://example.com/image85.jpg'),
(86, 'SKN086', 'Toner for Hyperpigmentation', 'FadeToner', 'Skincare', 'Toner',
 'hyperpigmentation,all', 'dark spots', 'Alpha-Arbutin, Licorice Root, Glycerin, Water', 22.00, 'USD', 150, 4.4, 130,
 'Gentle toner that helps fade pigmentation.', 'https://example.com/image86.jpg'),
(87, 'SKN087', 'Luxury Face Oil', 'GoldElixir', 'Skincare', 'Oil',
 'dry,normal', 'luxury glow', 'Marula Oil, Argan Oil, Squalane, Vitamin E', 45.00, 'USD', 30, 4.8, 100,
 'Premium face oil for rich nourishment.', 'https://example.com/image87.jpg'),
(88, 'SKN088', 'Water-Resistant Sunscreen SPF 30', 'ActiveShield', 'Skincare', 'Sunscreen',
 'all,especially for sports', 'sweat resistant', 'Zinc Oxide, Water, Silica, Dimethicone', 30.00, 'USD', 60, 4.7, 200,
 'Sunscreen built to resist sweat and water.', 'https://example.com/image88.jpg'),
(89, 'SKN089', 'Purifying Spot Gel', 'AcneErase', 'Skincare', 'Treatment',
 'acne-prone,oily', 'blemishes', 'Salicylic Acid, Tea Tree Oil, Water, Glycerin', 18.00, 'USD', 20, 4.2, 140,
 'Fast-acting spot treatment for acne.', 'https://example.com/image89.jpg'),
(90, 'SKN090', 'Soothing Gel Cream', 'CalmGel', 'Skincare', 'Moisturizer',
 'sensitive,redness', 'soothing,hydration', 'Aloe Vera, Glycerin, Panthenol, Water', 21.00, 'USD', 50, 4.5, 130,
 'Non-sticky gel cream for sensitive skin.', 'https://example.com/image90.jpg'),
(91, 'SKN091', 'Daily Detox Serum', 'DetoxPro', 'Skincare', 'Serum',
 'oily,combination', 'pollution,antioxidant', 'Vitamin C, Niacinamide, Green Tea, Water', 29.00, 'USD', 30, 140 * 0.01, 4.3, 120,
 'Serum that helps protect against environmental stress.', 'https://example.com/image91.jpg'),
(92, 'SKN092', 'Fragrance-Free Moisturizer', 'PureMoist', 'Skincare', 'Moisturizer',
 'sensitive,all', 'hydration', 'Glycerin, Ceramide, Water, Squalane', 24.00, 'USD', 50, 4.6, 150,
 'Gentle, fragrance-free moisturizer.', 'https://example.com/image92.jpg'),
(93, 'SKN093', 'Mineral Blush Compact', 'SoftBlush', 'Makeup', 'Blush',
 'all', 'color', 'Mica, Talc, Iron Oxides, Zinc Stearate', 21.00, 'USD', 10, 4.2, 90,
 'Natural finish mineral blush.', 'https://example.com/image93.jpg'),
(94, 'SKN094', 'Cream Highlighter Palette', 'GlowPalette', 'Makeup', 'Highlighter',
 'all', 'radiance', 'Mica, Shea Butter, Dimethicone, Talc', 32.00, 'USD', 18, 4.5, 110,
 'Palette with multiple cream highlighter shades.', 'https://example.com/image94.jpg'),
(95, 'SKN095', 'Setting Spray Matte Finish', 'MatteLock', 'Makeup', 'Setting Spray',
 'all', 'long wear,oil control', 'Water, Alcohol, Silica, Fragrance', 16.00, 'USD', 120, 4.1, 100,
 'Spray that keeps makeup matte all day.', 'https://example.com/image95.jpg'),
(96, 'SKN096', 'Liquid Bronzer', 'SunBronze', 'Makeup', 'Bronzer',
 'all', 'warmth,definition', 'Water, Iron Oxides, Silica, Glycerin', 22.50, 'USD', 30, 4.3, 120,
 'Lightweight bronzer for a sun-kissed look.', 'https://example.com/image96.jpg'),
(97, 'SKN097', 'Gentle Lip Scrub', 'SugarScrub', 'Makeup', 'Lip Care',
 'all', 'exfoliation', 'Sugar, Coconut Oil, Vitamin E, Shea Butter', 9.00, 'USD', 15, 4.4, 110,
 'Exfoliating lip scrub for smooth lips.', 'https://example.com/image97.jpg'),
(98, 'SKN098', 'Long-Wear Liquid Lipstick', 'StayMatte', 'Makeup', 'Lipstick',
 'all', 'long wear,color', 'Dimethicone, Iron Oxides, Water, Silica', 18.00, 'USD', 5, 4.2, 130,
 'Liquid lipstick with matte finish.', 'https://example.com/image98.jpg'),
(99, 'SKN099', 'Silk Finish Loose Powder', 'SoftSet', 'Makeup', 'Powder',
 'all', 'set makeup,finish', 'Silica, Talc, Magnesium Stearate', 20.00, 'USD', 25, 4.1, 100,
 'Fine loose powder for silky finish.', 'https://example.com/image99.jpg'),
(100, 'SKN100', 'Hydrating Face Primer', 'HydraPrime', 'Makeup', 'Primer',
 'dry,normal', 'hydration,base', 'Glycerin, Water, Dimethicone, Hyaluronic Acid', 23.00, 'USD', 30, 4.4, 130,
 'Hydrating primer to prep skin for makeup.', 'https://example.com/image100.jpg');
